# Generated by Django 2.2.12 on 2020-09-14 14:26

import agency.classes.choices
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Provincia')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='Codice')),
            ],
        ),
        migrations.CreateModel(
            name='AddressNation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Nazione')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='Codice')),
                ('lettersCode', models.CharField(db_index=True, max_length=5, verbose_name='Sigla')),
                ('prefix', models.CharField(max_length=5, null=True, verbose_name='Sigla')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(agency.classes.choices.RoleTag('ADMIN'), 'ADMIN'), (agency.classes.choices.RoleTag('OPERATOR'), 'OPERATOR')], max_length=30, verbose_name='Nome')),
                ('description', models.CharField(max_length=150, null=True, verbose_name='Descrizione')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='SettingsRAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.CharField(max_length=200, null=True, verbose_name='Email')),
                ('issuerCode', models.CharField(max_length=128, verbose_name='issuerCode')),
                ('host', models.CharField(max_length=200, null=True, verbose_name='Host email')),
                ('username', models.CharField(max_length=200, null=True, verbose_name='Configurazione email')),
                ('password', models.CharField(max_length=500, null=True, verbose_name='Password email')),
                ('port', models.CharField(max_length=4, null=True, verbose_name='Porta SMTP email')),
                ('crypto', models.CharField(choices=[(agency.classes.choices.CryptoTag('NESSUNA'), 'NESSUNA'), (agency.classes.choices.CryptoTag('TLS'), 'TLS'), (agency.classes.choices.CryptoTag('SSL'), 'SSL')], max_length=10, null=True, verbose_name='Crittografia')),
            ],
            options={
                'verbose_name': 'SettingsRAO',
            },
        ),
        migrations.CreateModel(
            name='SetupTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(verbose_name='Percentuale')),
                ('status', models.CharField(choices=[('in_progress', 'In Corso'), ('failed', 'Fallito'), ('completed', 'Completato')], max_length=30)),
                ('error', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TokenUser',
            fields=[
                ('uuid_token_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_user', models.TextField(null=True, verbose_name='Token Utente')),
                ('timestamp_creation', models.DateTimeField(null=True, verbose_name='Data creazione')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=200, verbose_name='uuid')),
                ('isVerified', models.BooleanField(default=False, verbose_name='Verificato')),
                ('creationDate', models.DateTimeField(null=True, verbose_name='Data creazione UTC')),
                ('expiredDate', models.DateTimeField(null=True, verbose_name='Data scadenza UTC')),
                ('email', models.CharField(db_index=True, max_length=200, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=500, verbose_name='Password')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Nome')),
                ('surname', models.CharField(db_index=True, max_length=30, verbose_name='Cognome')),
                ('fiscalNumber', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Codice Fiscale')),
                ('status', models.BooleanField(db_index=True, default=False, verbose_name='Stato')),
                ('signStatus', models.BooleanField(db_index=True, default=False, verbose_name='Stato')),
                ('failureTimestamp', models.DateTimeField(null=True, verbose_name='Data tentativo errato')),
                ('failureCounter', models.SmallIntegerField(default=0, verbose_name='Contatore tentativi errati')),
                ('idRole', models.ForeignKey(on_delete=None, to='agency.Role', verbose_name='Ruolo')),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'index_together': {('fiscalNumber', 'email'), ('fiscalNumber', 'name'), ('fiscalNumber', 'idRole'), ('name', 'surname'), ('fiscalNumber', 'surname'), ('fiscalNumber', 'status')},
            },
        ),
        migrations.CreateModel(
            name='IdentityRequest',
            fields=[
                ('uuid_identity', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fiscalNumberUser', models.CharField(db_index=True, max_length=16, null=True, verbose_name='Codice Fiscale')),
                ('status', models.SmallIntegerField(db_index=True, default=0, verbose_name='Stato')),
                ('timestamp_identification', models.DateTimeField(null=True, verbose_name='Data Identificazione')),
                ('idOperator', models.ForeignKey(on_delete=None, to='agency.Operator', verbose_name='Operatore')),
                ('token', models.ForeignKey(on_delete=None, to='agency.TokenUser', verbose_name='Token Utente')),
            ],
            options={
                'verbose_name': 'Identity',
                'verbose_name_plural': 'Identity',
            },
        ),
        migrations.CreateModel(
            name='AddressMunicipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Comune')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='Codice')),
                ('dateStart', models.DateField(null=True, verbose_name='Data Inizio')),
                ('dateEnd', models.DateField(null=True, verbose_name='Data Fine')),
                ('city', models.ForeignKey(max_length=100, on_delete=None, related_name='Città', to='agency.AddressCity', verbose_name='Città')),
            ],
        ),
    ]
