# Generated by Django 2.2.12 on 2021-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='isActivated',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Stato di attivazione'),
        ),
    ]
